[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust"
crate-type = ["lib", "staticlib", "cdylib"]
# crate-type = ["lib"]

[dependencies]
# anyhow = "1"
flutter_rust_bridge = "1"
nakamoto = { git = "https://github.com/cloudhead/nakamoto", branch = "master" }
# bdk = { version = "0.28", default-features = false , features = ["std"] }
silentpayments = { git = "https://github.com/cygnet3/rust-silentpayments", branch = "master" }
lazy_static = "1.4"
electrum-client = { git = "https://github.com/cygnet3/rust-electrum-client", branch = "sp_tweaks" }
anyhow = "1.0"
serde = { version = "1.0.188", features = ["derive"] }
# serde_json = "1.0.107"
turbosql = "0.8.0"
bitcoin = { version = "0.29.2", features = ["serde"] }
once_cell = "1.18.0"
bip39 = "2.0.0"
hex = "0.4.3"

[patch.crates-io]
ring = { path = "../../../rust/ringcrate/ring-0.16.20" }
